# Generated by Django 4.2.4 on 2023-08-19 08:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bodydata", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bodydata",
            name="created_at",
            field=models.DateField(unique=True, verbose_name="登録日時"),
        ),
    ]
