# Generated by Django 4.2.4 on 2023-08-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_customuser_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="gender",
            field=models.IntegerField(
                choices=[(1, "男性"), (2, "女性")], default=1, verbose_name="性別"
            ),
        ),
    ]
